to_do_list/to_do_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import todolist.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'todo/', include(todolist.urls)),
]

to_do_list/todolist/urls.py
from django.urls import path, include
from . import views

app_name = 'todolist'
urlpatterns = [
    path('home/', views.home, name='主页'),
    path('about/', views.about, name='关于'),
    path('edit/<每一件事_id>', views.edit, name='编辑'),
    path('del/<每一件事_id>', views.delete, name='删除'),
    path('cross/<每一件事_id>', views.cross, name='划掉'),
]

to_do_list/todolist/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    thing = models.CharField(max_length=50)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.thing

to_do_list/todolist/views.py
from django.shortcuts import render, redirect
from .models import Todo
# Create your views here.



def home(request):
    # request.POST
    if request.method == 'POST':
        if request.POST['待办事项'] == '':
            content = {'清单': Todo.objects.all(), '警告': '请收入内容！'}
            return render(request, 'todolist/home.html', content) 
        else:
            # lst.append({'待办事项':request.POST['待办事项'], '已完成': False})
            a_row = Todo(thing=request.POST['待办事项'], done=False)
            a_row.save()
            content = {'清单': Todo.objects.all(), '信息': '添加成功！'}
            return render(request, 'todolist/home.html', content)
    elif request.method == 'GET':
        content = {'清单': Todo.objects.all()}
        return render(request, 'todolist/home.html', content)

def about(request):
    return render(request, 'todolist/about.html')

def edit(request, 每一件事_id):
    if request.method == 'POST': 
        if request.POST['已修改事项'] == '':
           return render(request, 'todolist/edit.html', {'警告': '请收入内容！'})
        else:
            a = Todo.objects.get(id=每一件事_id)
            a.thing = request.POST['已修改事项']
            a.save()
            return redirect('todolist:主页')

    elif request.method == 'GET':
        content = {'待修改事项': Todo.objects.get(id=每一件事_id).thing }
        return render(request, 'todolist/edit.html', content)

def delete(request, 每一件事_id):
    a = Todo.objects.get(id=每一件事_id)
    a.delete()
    return redirect('todolist:主页')

def cross(request, 每一件事_id):
    if request.POST['完成状态'] == '已完成':
        a = Todo.objects.get(id=每一件事_id)
        a.done = True
        a.save()
        return redirect('todolist:主页')
    elif request.POST['完成状态'] == '未完成':
        a = Todo.objects.get(id=每一件事_id)
        a.done = False
        a.save()
        return redirect('todolist:主页')

to_do_list/todolist/templates/edit.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>编辑待办事项</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        #topnav{
            font-size: 1.35em;
            padding-left: 5em;
            padding-right: 5em;
            height: 2.5em;
        }
        nav input{
          width: 39%!important;
        }
        #form-edit{
           margin-left:8em;
           margin-right:8em;
        }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link" href="#">待办清单</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end">
          <input class="form-control mr-sm-2 " type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">添加</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <br>
      <form id="form-edit">
        <div class="form-group">
          <label for="editTodo"></label>
          <input class="form-control form-control-lg" id="editTodo" type="text" value="遛狗">
          <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
        </div>
        <button type="button" class="btn btn-primary btn-lg btn-block">提交</button>
      </form>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

to_do_list/todolist/templates/todolist/about.html
{% extends "todolist/base.html" %}
{% block 标题 %}关于本站{% endblock 标题 %}
{% block 关于高亮 %}active{% endblock 关于高亮 %}
{% block 主体 %}
<br>
<h4>一款小巧、简洁的待办清单工具，帮你规划日常事务。</h4>
{% endblock 主体 %}
    

to_do_list/todolist/templates/todolist/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block 标题 %}未命名{% endblock 标题 %}</title>

    <!-- lable icon -->
    <link href="{% static 'todolist/icons/icon_list.png' %}" rel="shortcut icon" />

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'todolist/css/base.css' %}">
    <link rel="stylesheet" href="{% block css %}{% endblock css %}">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block 主页高亮 %}{% endblock 主页高亮 %}">
            <a class="nav-link" href="{% url 'todolist:主页' %}"><img src="{% static 'todolist/images/logo_list.png' %}" width="33" height="33" class="d-inline-block align-top" alt=""> 待办清单</a>
          </li>
          <li class="nav-item {% block 关于高亮 %}{% endblock 关于高亮 %}">
            <a class="nav-link" href="{% url 'todolist:关于' %}">关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end" method='POST' action=''>
          {% csrf_token %}
          <input name='待办事项' class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      {% block 主体 %}
      {% endblock 主体 %}
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </body>
</html>

to_do_list/todolist/templates/todolist/edit.html
{% extends "todolist/base.html" %}
{% load static %}

{% block css %}{% static 'todolist/css/edit.css' %}{% endblock css %}

{% block 标题 %}编辑待办事项{% endblock 标题 %}
{% block 主体 %}
<br>  
<form id="form-edit" method="POST" action="">
  {% csrf_token %}
  <div class="form-group">
    <label for="editTodo"></label>
    <input name="已修改事项" class="form-control form-control-lg" id="editTodo" type="text" value="{{ 待修改事项 }}">
    <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
  </div>

  {% if 警告 %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong><center>{{ 警告 }}</center></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
  </div>
  {% endif %}

  <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
{% endblock 主体 %}

to_do_list/todolist/templates/todolist/home.html
{% extends "todolist/base.html" %}

{% load static %}

{% block css %}{% static 'todolist/css/home.css' %}{% endblock css %}

{% block 标题 %}你的个人待办清单{% endblock 标题 %}
{% block 主页高亮 %}active{% endblock 主页高亮 %}
{% block 主体 %}

{% if 警告 %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<strong><center>{{ 警告 }}</center></strong>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endif %}

{% if 信息 %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    <strong><center>{{ 信息 }}</center></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
{% endif %}

<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>序号</th>
        <th>待办事项</th>
        <th>编辑</th>
        <th>划掉</th>
        <th>删除</th>
      </tr>
    </thead>
    <tbody class="no-underline">
{% for 每一件事 in 清单  %}

{% if 每一件事.done %}
<tr class="table-dark">
  <th class="text-dark" scope="row">{{ 每一件事.id }}</th>
  <td class="text-dark" id="line-through">{{ 每一件事.thing }}</td>
  <td class="text-secondary">不可编辑</td>
  <td>
      <form method="POST" action="{% url 'todolist:划掉' 每一件事.id %}">
          {% csrf_token %}
          <input name="完成状态" type="hidden" value="未完成" >
      <button type="submit" class="btn btn-primary btn-sm">撤销</button>
      </form>
  </td>
  <td>
      <form method="POST" action="{% url 'todolist:删除' 每一件事.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">删除</button>
      </form>
   </td>
</tr>
{% else %}

<tr>
  <th scope="row">{{ 每一件事.id }}</th>
  <td>{{ 每一件事.thing }}</td>
  <td><a href="{% url 'todolist:编辑' 每一件事.id %}">
    <button type="submit" class="btn btn-primary btn-sm"> 
    编辑</button></a></td>
  <td>
  <form method="POST" action="{% url 'todolist:划掉' 每一件事.id %}">
      {% csrf_token %}
      <input name="完成状态" type="hidden" value="已完成" >
  <button type="submit" class="btn btn-primary btn-sm">划掉</button>
  </form>
  </td>

  <td>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal{{ forloop.counter }}">删除</button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModal{{ forloop.counter }}Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModal{{ forloop.counter }}Label">请确认</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
         确定要删除：<strong>未办事项 {{ 每一件事.thing }}</strong> 吗？
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"> 取消</button>
        <form method="POST" action="{% url 'todolist:删除' 每一件事.id %}">
          {% csrf_token %}       
          <button type="submit" class="btn btn-primary">确认</button>
        </form>
        </div>
      </div>
    </div>
  </div>
</td>

</tr>
{% endif %}



{% endfor %}

    </tbody>
  </table>

</div>
{% endblock 主体 %}